# Generated by Django 5.0.6 on 2024-06-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_questions_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='answer',
            field=models.BooleanField(default=False, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='user_quiz',
            name='privacy',
            field=models.BooleanField(default=False, verbose_name='private'),
        ),
    ]
