# Generated by Django 5.0.6 on 2024-06-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_option_answer_user_quiz_privacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='answer',
        ),
        migrations.AddField(
            model_name='option',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='is_correct'),
        ),
    ]
