# Generated by Django 5.0.6 on 2024-06-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_option_answer_option_is_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='option_type',
        ),
        migrations.AlterField(
            model_name='user_quiz',
            name='privacy',
            field=models.BooleanField(default=False, verbose_name='privacy'),
        ),
        migrations.AlterField(
            model_name='user_quiz',
            name='reattempt',
            field=models.BooleanField(default=True, verbose_name='reattempt'),
        ),
    ]
